In [1]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import os
from pydataset import data

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import acquire1
import env

import prepare

import graphviz
from graphviz import Graph

In [ ]:
#acquire and prepare my dataset
train, validate, test = prepare.prep_titanic_data(acquire1.get_titanic_data())

In [ ]:
train.head()

In [ ]:
#drop columns I won't need
train.drop(columns=['sex', 'embark_town'], inplace=True)
validate.drop(columns=['sex', 'embark_town'], inplace=True)
test.drop(columns=['sex', 'embark_town'], inplace=True)

In [ ]:
train.head()

What is your baseline prediction? What is your baseline accuracy? remember: your baseline prediction for a classification problem is predicting the most prevelant class in the training dataset (the mode). When you make those predictions, what is your accuracy? This is your baseline accuracy.

In [ ]:
#create baseline
train['baseline']= 0

In [ ]:
train.head()

In [ ]:
#check accuracy of baseline
accuracy = (train.survived == train.baseline).mean()
accuracy

In [ ]:
#drop baseline column after getting the accuracy since we don't need it any longer
# Remove two columns name is 'C' and 'D'
#df.drop(['C', 'D'], axis = 1) example
train.drop('baseline', axis =1)

2. Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [39]:
#create the object
clf = DecisionTreeClassifier(max_depth=3, random_state=123)

In [ ]:
# create X & y version of train, where y is a series with just the target variable and X are all the features. 

X_train = train.drop(columns=['survived'])
y_train = train.survived

X_validate = validate.drop(columns=['survived'])
y_validate = validate.survived

X_test = test.drop(columns=['survived'])
y_test = test.survived

In [ ]:
# model.fit(X, y)

clf = clf.fit(X_train, y_train)

In [ ]:
dot_data = export_graphviz(clf, feature_names= X_train.columns, class_names=('survived', 'died'), rounded=True, filled=True, out_file=None)
graph = graphviz.Source(dot_data) 

graph.render('titanic_decision_tree', view=True)

3. Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [ ]:
#finding model score
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
      .format(clf.score(X_train, y_train)))

In [ ]:
y_pred = clf.predict(X_train)
y_pred[0:5]

In [ ]:
#create a confusion matrix
confusion_matrix(y_train, y_pred)

In [ ]:
labels = sorted(y_train.unique())

pd.DataFrame(confusion_matrix(y_train, y_pred), index=labels, columns=labels)

In [ ]:
#print classification report
print(classification_report(y_train, y_pred))

4. Compute: Accuracy, true positive rate(recall), false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [ ]:
#create a confusion matrix
confusion_matrix(y_train, y_pred)

Run through steps 2-4 using a different max_depth value.

2. Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [ ]:
#create the object
clf = DecisionTreeClassifier(max_depth=4, random_state=123)

In [ ]:
# model.fit(X, y)

clf = clf.fit(X_train, y_train)

In [ ]:
X_train.head()

In [ ]:
X_validate.head()

In [ ]:
#create decision tree .pdf
dot_data = export_graphviz(clf, feature_names= X_train.columns, class_names=('survived', 'died'), rounded=True, filled=True, out_file=None)
graph = graphviz.Source(dot_data) 

graph.render('titanic_decision_tree', view=True)

3. Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [ ]:
#finding model score
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
      .format(clf.score(X_train, y_train)))

In [ ]:
#clf.predict(X_train) uses the model to create a prediction for each row in the X_train dataframe and each prediction is
# based on the specific features and their values in that given row...one prediction for each row in that dataframe
y_pred = clf.predict(X_train)
y_pred[0:5]

In [ ]:
#create a confusion matrix
confusion_matrix(y_train, y_pred)

In [ ]:
labels = sorted(y_train.unique())

pd.DataFrame(confusion_matrix(y_train, y_pred), index=labels, columns=labels)


In [ ]:
#print classification report
print(classification_report(y_train, y_pred))

Compute: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.(See above)

6. Which model performs better on your in-sample data?
The second model with depth of 4 performs better.

7. Which model performs best on your out-of-sample data, the validate set?

In [ ]:
train.shape

In [ ]:
train.head()

In [ ]:
train.drop('baseline', axis =1, inplace=True)

In [ ]:
train.shape

In [ ]:
validate.shape

In [ ]:
print('Accuracy of Decision Tree classifier on validate set: {:.2f}'
     .format(clf.score(X_validate, y_validate)))

the model is trained on train, and we’ll use that same model to run .predict on X_train, then X_validate, and eventually X_test

In [ ]:
train.head()
validate.head()

In [ ]:
# And since accuracy isn't everything

# Produce y_predictions that come from the X_validate
y_pred = clf.predict(X_validate)

# Compare actual y values (from validate) to predicted y_values from the model run on X_validate
print(classification_report(y_validate, y_pred))

In [ ]:
######################################## Random Forest

Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 10.

Evaluate your results using the model score, confusion matrix, and classification report.

Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

Run through steps increasing your min_samples_leaf and decreasing your max_depth.

What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?

After making a few models, which one has the best performance (or closest metrics) on both train and validate?

In [2]:
#acquire the data
# read Iris data from pydatset
df = data('iris')

# convert column names to lowercase, replace '.' in column names with '_'
df.columns = [col.lower().replace('.', '_') for col in df]

#inspect the data
df.head()

sepal_length  sepal_width  petal_length  petal_width species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [3]:
target = 'species'

In [4]:
def train_validate_test_split(df, target, seed=123):
    '''
    This function takes in a dataframe, the name of the target variable
    (for stratification purposes), and an integer for a setting a seed
    and splits the data into train, validate and test. 
    Test is 20% of the original dataset, validate is .30*.80= 24% of the 
    original dataset, and train is .70*.80= 56% of the original dataset. 
    The function returns, in this order, train, validate and test dataframes. 
    '''
    train_validate, test = train_test_split(df, test_size=0.2, 
                                            random_state=seed, 
                                            stratify=df[target])
    train, validate = train_test_split(train_validate, test_size=0.3, 
                                       random_state=seed,
                                       stratify=train_validate[target])
    return train, validate, test

In [5]:
# split into train, validate, test
train, validate, test = train_validate_test_split(df, target='species', seed=123)

# create X & y version of train, where y is a series with just the target variable and X are all the features. 

X_train = train.drop(columns=['species'])
y_train = train.species

X_validate = validate.drop(columns=['species'])
y_validate = validate.species

X_test = test.drop(columns=['species'])
y_test = test.species

In [6]:
train.head()

sepal_length  sepal_width  petal_length  petal_width     species
80            5.7          2.6           3.5          1.0  versicolor
37            5.5          3.5           1.3          0.2      setosa
134           6.3          2.8           5.1          1.5   virginica
96            5.7          3.0           4.2          1.2  versicolor
19            5.7          3.8           1.7          0.3      setosa

Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 10.

In [7]:
#create the object
rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=1,
                            n_estimators=100,
                            max_depth=10, 
                            random_state=123)

In [8]:
#Fit the random forest algorithm to the training data.

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=123)

In [9]:
print(rf.feature_importances_)

[0.08535086 0.04093506 0.4784486  0.39526548]


Evaluate your results using the model score, confusion matrix, and classification report.

In [10]:
#Make Predictions classify each flower by its estimated species.
y_pred = rf.predict(X_train)

In [11]:
#Estimate the probability of each species, using the training data
y_pred_proba = rf.predict_proba(X_train)

2. Evaluate your results using the model score, confusion matrix, and classification report.

In [12]:
#finding model score
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf.score(X_train, y_train)))

Accuracy of random forest classifier on training set: 1.00


In [13]:
#create confusion matrix
confusion_matrix(y_train, y_pred)

array([[28,  0,  0],
       [ 0, 28,  0],
       [ 0,  0, 28]])

In [14]:
#print classification report
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      1.00      1.00        28
   virginica       1.00      1.00      1.00        28

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



3. Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [15]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf.score(X_train, y_train)))
print('True Positive Rate: {}')
print('False Positive Rate: {}')
print('True Negative Rate: {}')
print('False Negative Rate: {}')
print('Precision: {1.00}')
print('Recall: {1.00}')
print('F-1 Score: {1.00}')
print('Support: {28}')

Accuracy of random forest classifier on training set: 1.00
True Positive Rate: {}
False Positive Rate: {}
True Negative Rate: {}
False Negative Rate: {}
Precision: {1.00}
Recall: {1.00}
F-1 Score: {1.00}
Support: {28}


In [16]:
confusion_matrix(y_train, y_pred)

array([[28,  0,  0],
       [ 0, 28,  0],
       [ 0,  0, 28]])

Values gathered from confusion matrix above:

Setosa
TP = 28(cell1) where setosa meets setosa
FN = 0 (cell2 + cell3) setosa row other than TP
FP = 0 (cell4 + cell7) setosa column other than TP
TN = 56 (cell5 + cell6 + cell8 + cell9) everything other than setosa row and column

Versicolor
TP = 28 (cell5) where versicolor meets versicolor
FN = 0 (cell4 + cell6) versicolor row other than TP
FP = 0 (cell2 + cell8) versicolor column other than TP
TN = 28 (cell1 + cell3 + cell7 + cell9) everything other than versicolor row and column

Virginica
TP = 28
FN = 0
FP = 0
TN = 56

What is the difference between these values and the actual rate of each?

4. Run through steps increasing your min_samples_leaf and decreasing your max_depth.

In [17]:
#Test 1 change min_samples_leaf to 3 from 1

In [18]:
#create the object
rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=3,
                            n_estimators=100,
                            max_depth=10, 
                            random_state=123)

In [19]:
#Fit the random forest algorithm to the training data.

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=3, random_state=123)

In [20]:
print(rf.feature_importances_)

[0.07855762 0.0291349  0.48073357 0.41157391]


In [21]:
#Make Predictions classify each flower by its estimated species.
y_pred = rf.predict(X_train)

In [22]:
#Estimate the probability of each species, using the training data
y_pred_proba = rf.predict_proba(X_train)

In [23]:
#finding model score
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf.score(X_train, y_train)))

Accuracy of random forest classifier on training set: 0.98


In [24]:
#create confusion matrix
confusion_matrix(y_train, y_pred)

array([[28,  0,  0],
       [ 0, 26,  2],
       [ 0,  0, 28]])

In [25]:
#print classification report
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      0.93      0.96        28
   virginica       0.93      1.00      0.97        28

    accuracy                           0.98        84
   macro avg       0.98      0.98      0.98        84
weighted avg       0.98      0.98      0.98        84



In [26]:
# The results are decreased accuracy by .02 decreased recall, precision and f-1 by a small 
# amount

In [27]:
# TEST 2 change min_samples_leaf from 3 to 6

In [31]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=6,
                            n_estimators=100,
                            max_depth=10, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.08437474 0.0279723  0.47215105 0.4155019 ]
Accuracy of random forest classifier on training set: 0.98
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      0.93      0.96        28
   virginica       0.93      1.00      0.97        28

    accuracy                           0.98        84
   macro avg       0.98      0.98      0.98        84
weighted avg       0.98      0.98      0.98        84



In [30]:
test_my_model(df)

None


In [ ]:
 #create the object
rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=6,
                            n_estimators=100,
                            max_depth=10, 
                            random_state=123)
    

In [ ]:
#Fit the random forest algorithm to the training data.
rf.fit(X_train, y_train)

In [ ]:
print(rf.feature_importances_)

In [ ]:
#Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))

In [ ]:
# Results the accuracy and other measurements did not change at all or just in the smallest
# amount that did not seem significant

In [ ]:
# Test 3 change max depth from 10 to 5

In [32]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=1,
                            n_estimators=100,
                            max_depth=5, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.0850644  0.04051708 0.47973666 0.39468186]
Accuracy of random forest classifier on training set: 1.00
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      1.00      1.00        28
   virginica       1.00      1.00      1.00        28

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



In [ ]:
# Results this changes the accuracy back to 1 along with precision, recall, f1

In [ ]:
# Test 4 change max depth to 2 from 5

In [34]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=6,
                            n_estimators=100,
                            max_depth=2, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.08833352 0.02775966 0.46983979 0.41406704]
Accuracy of random forest classifier on training set: 0.98
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      0.93      0.96        28
   virginica       0.93      1.00      0.97        28

    accuracy                           0.98        84
   macro avg       0.98      0.98      0.98        84
weighted avg       0.98      0.98      0.98        84



In [ ]:
# Results also not much significant change

In [ ]:
# Test 5 change the leaf to 2 and keep depth at 2

In [36]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=4,
                            n_estimators=100,
                            max_depth=4, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.08040493 0.02838481 0.47775664 0.41345362]
Accuracy of random forest classifier on training set: 0.98
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      0.93      0.96        28
   virginica       0.93      1.00      0.97        28

    accuracy                           0.98        84
   macro avg       0.98      0.98      0.98        84
weighted avg       0.98      0.98      0.98        84



In [ ]:
# Result still no significant changes

5. What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?
The model performs best on max_depth of five and with min_samples_leaf at 1.  I'm not sure why though.

After making a few models, which one has the best performance (or closest metrics) on both train and validate? 

In [41]:
# find accuracy on validate data
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_validate, y_validate)))

Accuracy of random forest classifier on test set: 0.97


In [42]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=1,
                            n_estimators=100,
                            max_depth=5, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.0850644  0.04051708 0.47973666 0.39468186]
Accuracy of random forest classifier on training set: 1.00
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      1.00      1.00        28
   virginica       1.00      1.00      1.00        28

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



In [43]:
# find accuracy on validate data
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_validate, y_validate)))

Accuracy of random forest classifier on test set: 0.97


In [37]:
#This function should label and plot that array of feature importances if you just pass it 
# your classifier object.
def impurity_decrese_vs_feature_plot(clf):
    # Calculate standard deviation of mean impurity across all trees for each feature.
    std = np.std([
        tree.featureimportances for tree in clf.estimators_], axis=0)

    # Caluclate feature importances and label them with the columns from our train set.
    forest_importances = pd.Series(clf.featureimportances, index=X_train.columns)

    fig, ax = plt.subplots()
    forest_importances.plot.bar(yerr=std, ax=ax)
    ax.set_title("Feature importances using MDI")
    ax.set_ylabel("Mean decrease in impurity")
    fig.tight_layout()
    return fig

In [44]:
def test_my_model(df):
    #create the object
    rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=6,
                            n_estimators=100,
                            max_depth=2, 
                            random_state=123)
    #Fit the random forest algorithm to the training data.
    rf.fit(X_train, y_train)
    print(rf.feature_importances_)
    #Make Predictions classify each flower by its estimated species.
    y_pred = rf.predict(X_train)
    #Estimate the probability of each species, using the training data
    y_pred_proba = rf.predict_proba(X_train)
    #finding model score
    print('Accuracy of random forest classifier on training set: {:.2f}'
    .format(rf.score(X_train, y_train)))
    #create confusion matrix
    confusion_matrix(y_train, y_pred)
    #print classification report
    print(classification_report(y_train, y_pred))
    return
    
test_my_model(df)

[0.08833352 0.02775966 0.46983979 0.41406704]
Accuracy of random forest classifier on training set: 0.98
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       1.00      0.93      0.96        28
   virginica       0.93      1.00      0.97        28

    accuracy                           0.98        84
   macro avg       0.98      0.98      0.98        84
weighted avg       0.98      0.98      0.98        84



In [45]:
# find accuracy on validate data
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_validate, y_validate)))

Accuracy of random forest classifier on test set: 0.97


In [ ]:
# Can't figure out why my validate accuracy doesn't change, might be doing something
# wrong here

In [40]:
impurity_decrese_vs_feature_plot(clf)

AttributeError: 'DecisionTreeClassifier' object has no attribute 'estimators_'